# Single source of truth for the full CARDS taxonomy (88 entries).
# Used by CARDSMatcher (label lookup) and CARDSClassifier (display labels).

TAXONOMY: list[dict] = [
    {
        "id": "0",
        "url": "https://purl.net/climatesense/climafactskg/ns#0",
        "label": "Not climate misinformation or related to the climate.",
    },
    {"id": "1", "url": "https://purl.net/climatesense/climafactskg/ns#1", "label": "Global warming is not happening"},
    {
        "id": "2",
        "url": "https://purl.net/climatesense/climafactskg/ns#2",
        "label": "Human GHGs are not causing global warming",
    },
    {"id": "3", "url": "https://purl.net/climatesense/climafactskg/ns#3", "label": "Climate impacts are not bad"},
    {"id": "4", "url": "https://purl.net/climatesense/climafactskg/ns#4", "label": "Climate solutions won't work"},
    {
        "id": "5",
        "url": "https://purl.net/climatesense/climafactskg/ns#5",
        "label": "Climate movement/science is unreliable",
    },
    {"id": "1_1", "url": "https://purl.net/climatesense/climafactskg/ns#1_1", "label": "Ice isn't melting"},
    {"id": "1_2", "url": "https://purl.net/climatesense/climafactskg/ns#1_2", "label": "Heading into ice age"},
    {"id": "1_3", "url": "https://purl.net/climatesense/climafactskg/ns#1_3", "label": "Weather is cold"},
    {"id": "1_4", "url": "https://purl.net/climatesense/climafactskg/ns#1_4", "label": "Hiatus in warming"},
    {"id": "1_5", "url": "https://purl.net/climatesense/climafactskg/ns#1_5", "label": "Oceans are cooling"},
    {"id": "1_6", "url": "https://purl.net/climatesense/climafactskg/ns#1_6", "label": "See level rise is exagerated"},
    {"id": "1_7", "url": "https://purl.net/climatesense/climafactskg/ns#1_7", "label": "Extremes aren't increasing"},
    {"id": "1_8", "url": "https://purl.net/climatesense/climafactskg/ns#1_8", "label": "Changed the name"},
    {"id": "2_1", "url": "https://purl.net/climatesense/climafactskg/ns#2_1", "label": "It's natural cycles"},
    {"id": "2_2", "url": "https://purl.net/climatesense/climafactskg/ns#2_2", "label": "Non-GHG forcings"},
    {"id": "2_3", "url": "https://purl.net/climatesense/climafactskg/ns#2_3", "label": "No evidence for GHE"},
    {"id": "2_4", "url": "https://purl.net/climatesense/climafactskg/ns#2_4", "label": "CO2 not rising"},
    {
        "id": "2_5",
        "url": "https://purl.net/climatesense/climafactskg/ns#2_5",
        "label": "Emissions not raising CO2 levels",
    },
    {"id": "3_1", "url": "https://purl.net/climatesense/climafactskg/ns#3_1", "label": "Sensitivity is low"},
    {"id": "3_2", "url": "https://purl.net/climatesense/climafactskg/ns#3_2", "label": "No species impact"},
    {"id": "3_3", "url": "https://purl.net/climatesense/climafactskg/ns#3_3", "label": "Not a pollutant"},
    {"id": "3_4", "url": "https://purl.net/climatesense/climafactskg/ns#3_4", "label": "Only a few degrees"},
    {"id": "3_5", "url": "https://purl.net/climatesense/climafactskg/ns#3_5", "label": "No link to conflict"},
    {"id": "3_6", "url": "https://purl.net/climatesense/climafactskg/ns#3_6", "label": "No health impacts"},
    {"id": "4_1", "url": "https://purl.net/climatesense/climafactskg/ns#4_1", "label": "Policies are harmful"},
    {"id": "4_2", "url": "https://purl.net/climatesense/climafactskg/ns#4_2", "label": "Policies are ineffective"},
    {"id": "4_3", "url": "https://purl.net/climatesense/climafactskg/ns#4_3", "label": "Too hard"},
    {"id": "4_4", "url": "https://purl.net/climatesense/climafactskg/ns#4_4", "label": "Clean energy won't work"},
    {"id": "4_5", "url": "https://purl.net/climatesense/climafactskg/ns#4_5", "label": "We need energy"},
    {"id": "5_1", "url": "https://purl.net/climatesense/climafactskg/ns#5_1", "label": "Science is unreliable"},
    {"id": "5_2", "url": "https://purl.net/climatesense/climafactskg/ns#5_2", "label": "Movement is unreliable"},
    {"id": "5_3", "url": "https://purl.net/climatesense/climafactskg/ns#5_3", "label": "Climate is conspiracy"},
    {"id": "1_1_1", "url": "https://purl.net/climatesense/climafactskg/ns#1_1_1", "label": "Antartica isn't melting"},
    {"id": "1_1_2", "url": "https://purl.net/climatesense/climafactskg/ns#1_1_2", "label": "Greenland isn't melting"},
    {"id": "1_1_3", "url": "https://purl.net/climatesense/climafactskg/ns#1_1_3", "label": "Artic isn't melting"},
    {"id": "1_1_4", "url": "https://purl.net/climatesense/climafactskg/ns#1_1_4", "label": "Glaciers aren't vanishing"},
    {"id": "2_1_1", "url": "https://purl.net/climatesense/climafactskg/ns#2_1_1", "label": "It's the sun"},
    {"id": "2_1_2", "url": "https://purl.net/climatesense/climafactskg/ns#2_1_2", "label": "It's geological"},
    {"id": "2_1_3", "url": "https://purl.net/climatesense/climafactskg/ns#2_1_3", "label": "It's the ocean"},
    {"id": "2_1_4", "url": "https://purl.net/climatesense/climafactskg/ns#2_1_4", "label": "Past climate change"},
    {"id": "2_1_5", "url": "https://purl.net/climatesense/climafactskg/ns#2_1_5", "label": "Tiny CO2 emissions"},
    {"id": "2_3_1", "url": "https://purl.net/climatesense/climafactskg/ns#2_3_1", "label": "CO2 is trace gas"},
    {"id": "2_3_2", "url": "https://purl.net/climatesense/climafactskg/ns#2_3_2", "label": "GHE is saturated"},
    {"id": "2_3_3", "url": "https://purl.net/climatesense/climafactskg/ns#2_3_3", "label": "CO2 lags climate"},
    {"id": "2_3_4", "url": "https://purl.net/climatesense/climafactskg/ns#2_3_4", "label": "Water vapor"},
    {"id": "2_3_5", "url": "https://purl.net/climatesense/climafactskg/ns#2_3_5", "label": "Tropospheric hot spot"},
    {"id": "2_3_6", "url": "https://purl.net/climatesense/climafactskg/ns#2_3_6", "label": "CO2 high in past"},
    {"id": "3_2_1", "url": "https://purl.net/climatesense/climafactskg/ns#3_2_1", "label": "Species can adapt"},
    {"id": "3_2_2", "url": "https://purl.net/climatesense/climafactskg/ns#3_2_2", "label": "Polar bears ok"},
    {"id": "3_2_3", "url": "https://purl.net/climatesense/climafactskg/ns#3_2_3", "label": "Oceans are ok"},
    {"id": "3_3_1", "url": "https://purl.net/climatesense/climafactskg/ns#3_3_1", "label": "CO2 is plant food"},
    {"id": "4_1_1", "url": "https://purl.net/climatesense/climafactskg/ns#4_1_1", "label": "Policy increases costs"},
    {"id": "4_1_2", "url": "https://purl.net/climatesense/climafactskg/ns#4_1_2", "label": "Policy weakens security"},
    {"id": "4_1_3", "url": "https://purl.net/climatesense/climafactskg/ns#4_1_3", "label": "Policy harms environment"},
    {"id": "4_1_4", "url": "https://purl.net/climatesense/climafactskg/ns#4_1_4", "label": "Rich future generations"},
    {"id": "4_1_5", "url": "https://purl.net/climatesense/climafactskg/ns#4_1_5", "label": "Limits freedom"},
    {"id": "4_2_1", "url": "https://purl.net/climatesense/climafactskg/ns#4_2_1", "label": "Green jobs don't work"},
    {"id": "4_2_2", "url": "https://purl.net/climatesense/climafactskg/ns#4_2_2", "label": "Markets more efficient"},
    {
        "id": "4_2_3",
        "url": "https://purl.net/climatesense/climafactskg/ns#4_2_3",
        "label": "Policy impact is negligible",
    },
    {"id": "4_2_4", "url": "https://purl.net/climatesense/climafactskg/ns#4_2_4", "label": "One country is negligible"},
    {"id": "4_2_5", "url": "https://purl.net/climatesense/climafactskg/ns#4_2_5", "label": "Better to adapt"},
    {"id": "4_2_6", "url": "https://purl.net/climatesense/climafactskg/ns#4_2_6", "label": "China's emissions"},
    {"id": "4_2_7", "url": "https://purl.net/climatesense/climafactskg/ns#4_2_7", "label": "Techno fix"},
    {"id": "4_3_1", "url": "https://purl.net/climatesense/climafactskg/ns#4_3_1", "label": "Policy too difficult"},
    {"id": "4_3_2", "url": "https://purl.net/climatesense/climafactskg/ns#4_3_2", "label": "Low public support"},
    {"id": "4_4_1", "url": "https://purl.net/climatesense/climafactskg/ns#4_4_1", "label": "Clean energy unreliable"},
    {"id": "4_4_2", "url": "https://purl.net/climatesense/climafactskg/ns#4_4_2", "label": "CCS is unproven"},
    {"id": "4_5_1", "url": "https://purl.net/climatesense/climafactskg/ns#4_5_1", "label": "FF is plentiful"},
    {"id": "4_5_2", "url": "https://purl.net/climatesense/climafactskg/ns#4_5_2", "label": "FF are cheap"},
    {"id": "4_5_3", "url": "https://purl.net/climatesense/climafactskg/ns#4_5_3", "label": "Nuclear is good"},
    {"id": "5_1_1", "url": "https://purl.net/climatesense/climafactskg/ns#5_1_1", "label": "No consensus"},
    {"id": "5_1_2", "url": "https://purl.net/climatesense/climafactskg/ns#5_1_2", "label": "Proxies are unreliable"},
    {"id": "5_1_3", "url": "https://purl.net/climatesense/climafactskg/ns#5_1_3", "label": "Temp is unreliable"},
    {"id": "5_1_4", "url": "https://purl.net/climatesense/climafactskg/ns#5_1_4", "label": "Models are unreliable"},
    {"id": "5_2_1", "url": "https://purl.net/climatesense/climafactskg/ns#5_2_1", "label": "Climate is religion"},
    {"id": "5_2_2", "url": "https://purl.net/climatesense/climafactskg/ns#5_2_2", "label": "Media is alarmist"},
    {"id": "5_2_3", "url": "https://purl.net/climatesense/climafactskg/ns#5_2_3", "label": "Politicians are biased"},
    {
        "id": "5_2_4",
        "url": "https://purl.net/climatesense/climafactskg/ns#5_2_4",
        "label": "Environmentalists are alarmist",
    },
    {"id": "5_2_5", "url": "https://purl.net/climatesense/climafactskg/ns#5_2_5", "label": "Scientist are biased"},
    {"id": "5_3_1", "url": "https://purl.net/climatesense/climafactskg/ns#5_3_1", "label": "Policy is conspiracy"},
    {"id": "5_3_2", "url": "https://purl.net/climatesense/climafactskg/ns#5_3_2", "label": "Science is conspiracy"},
    # Parent-level fallback codes (when subcategory cannot be determined) and topic gate
    {
        "id": "0_0",
        "url": "https://purl.net/climatesense/climafactskg/ns#0_0",
        "label": "Climate-related but not misinformation",
    },
    {
        "id": "1_0",
        "url": "https://purl.net/climatesense/climafactskg/ns#1_0",
        "label": "Global warming is not happening (general)",
    },
    {
        "id": "2_0",
        "url": "https://purl.net/climatesense/climafactskg/ns#2_0",
        "label": "Human GHGs are not causing global warming (general)",
    },
    {
        "id": "3_0",
        "url": "https://purl.net/climatesense/climafactskg/ns#3_0",
        "label": "Climate impacts are not bad (general)",
    },
    {
        "id": "4_0",
        "url": "https://purl.net/climatesense/climafactskg/ns#4_0",
        "label": "Climate solutions won't work (general)",
    },
    {
        "id": "5_0",
        "url": "https://purl.net/climatesense/climafactskg/ns#5_0",
        "label": "Climate movement/science is unreliable (general)",
    },
]
